# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 82a1d6079debc05b19f28a083aff51c20e308141ce81133092626e9d2fbbb888ba5b0f0ccc0dadc8682ae227cafc888ee645236e8d6297ae391762716273f4e8

test:
  secret_key_base: 962a95e587648e65ae690e8b93d8e9e872ee8ed467db6983f5e392916c51a476e1bf6aaad3a0fbd9ef30aa8ede9437f792ddd025e4e4de62af3fbe8b1380a929

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
