# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a5b5c41cd923d473292c87b78d5da4005b417e1285fab6df1b7658c6fea8339a1e9bc54e055bf4066773eb4b93a7c890aac1c5fa7595128602ca2d5b786cb78d

test:
  secret_key_base: 9a6f77bbc35219f404ce1f46fe7e1ec5da9e0495938621b402a969ba5e1893620029486a557b3b791ad54c3973689ea4281c07b41f24ff448c1273729fabc462

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
